// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: internal/app/adapter/inbound/grpc/article.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllArticleRequest) Reset() {
	*x = GetAllArticleRequest{}
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArticleRequest) ProtoMessage() {}

func (x *GetAllArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArticleRequest.ProtoReflect.Descriptor instead.
func (*GetAllArticleRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllArticleRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllArticleRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetAllArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*ArticleResponse     `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalCount    int64                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllArticleResponse) Reset() {
	*x = GetAllArticleResponse{}
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArticleResponse) ProtoMessage() {}

func (x *GetAllArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArticleResponse.ProtoReflect.Descriptor instead.
func (*GetAllArticleResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllArticleResponse) GetArticles() []*ArticleResponse {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *GetAllArticleResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAllArticleResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetAllArticleResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetArticleByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIdRequest) Reset() {
	*x = GetArticleByIdRequest{}
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIdRequest) ProtoMessage() {}

func (x *GetArticleByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIdRequest.ProtoReflect.Descriptor instead.
func (*GetArticleByIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticleResponse       `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIdResponse) Reset() {
	*x = GetArticleByIdResponse{}
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIdResponse) ProtoMessage() {}

func (x *GetArticleByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIdResponse.ProtoReflect.Descriptor instead.
func (*GetArticleByIdResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleByIdResponse) GetArticle() *ArticleResponse {
	if x != nil {
		return x.Article
	}
	return nil
}

type ArticleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug            string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ContentMarkdown string                 `protobuf:"bytes,4,opt,name=content_markdown,json=contentMarkdown,proto3" json:"content_markdown,omitempty"`
	ContentHtml     string                 `protobuf:"bytes,5,opt,name=content_html,json=contentHtml,proto3" json:"content_html,omitempty"`
	ContentJson     string                 `protobuf:"bytes,6,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	IsDraft         bool                   `protobuf:"varint,7,opt,name=is_draft,json=isDraft,proto3" json:"is_draft,omitempty"`
	PublishedAt     string                 `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	UpvoteCount     int32                  `protobuf:"varint,9,opt,name=upvote_count,json=upvoteCount,proto3" json:"upvote_count,omitempty"`
	IsUpvoted       bool                   `protobuf:"varint,10,opt,name=is_upvoted,json=isUpvoted,proto3" json:"is_upvoted,omitempty"`
	ViewCount       int32                  `protobuf:"varint,11,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	IsViewed        bool                   `protobuf:"varint,12,opt,name=is_viewed,json=isViewed,proto3" json:"is_viewed,omitempty"`
	LatestViewedAt  string                 `protobuf:"bytes,13,opt,name=latest_viewed_at,json=latestViewedAt,proto3" json:"latest_viewed_at,omitempty"`
	CategoryId      uint64                 `protobuf:"varint,14,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagIds          []string               `protobuf:"bytes,15,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	User            *UserResponse          `protobuf:"bytes,16,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArticleResponse) Reset() {
	*x = ArticleResponse{}
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResponse) ProtoMessage() {}

func (x *ArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResponse.ProtoReflect.Descriptor instead.
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArticleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ArticleResponse) GetContentMarkdown() string {
	if x != nil {
		return x.ContentMarkdown
	}
	return ""
}

func (x *ArticleResponse) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *ArticleResponse) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *ArticleResponse) GetIsDraft() bool {
	if x != nil {
		return x.IsDraft
	}
	return false
}

func (x *ArticleResponse) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *ArticleResponse) GetUpvoteCount() int32 {
	if x != nil {
		return x.UpvoteCount
	}
	return 0
}

func (x *ArticleResponse) GetIsUpvoted() bool {
	if x != nil {
		return x.IsUpvoted
	}
	return false
}

func (x *ArticleResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ArticleResponse) GetIsViewed() bool {
	if x != nil {
		return x.IsViewed
	}
	return false
}

func (x *ArticleResponse) GetLatestViewedAt() string {
	if x != nil {
		return x.LatestViewedAt
	}
	return ""
}

func (x *ArticleResponse) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ArticleResponse) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *ArticleResponse) GetUser() *UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_inbound_grpc_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_internal_app_adapter_inbound_grpc_article_proto protoreflect.FileDescriptor

const file_internal_app_adapter_inbound_grpc_article_proto_rawDesc = "" +
	"\n" +
	"/internal/app/adapter/inbound/grpc/article.proto\x12\x04grpc\">\n" +
	"\x14GetAllArticleRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xaf\x01\n" +
	"\x15GetAllArticleResponse\x121\n" +
	"\barticles\x18\x01 \x03(\v2\x15.grpc.ArticleResponseR\barticles\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x03R\n" +
	"totalCount\"'\n" +
	"\x15GetArticleByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x16GetArticleByIdResponse\x12/\n" +
	"\aarticle\x18\x01 \x01(\v2\x15.grpc.ArticleResponseR\aarticle\"\x84\x04\n" +
	"\x0fArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12)\n" +
	"\x10content_markdown\x18\x04 \x01(\tR\x0fcontentMarkdown\x12!\n" +
	"\fcontent_html\x18\x05 \x01(\tR\vcontentHtml\x12!\n" +
	"\fcontent_json\x18\x06 \x01(\tR\vcontentJson\x12\x19\n" +
	"\bis_draft\x18\a \x01(\bR\aisDraft\x12!\n" +
	"\fpublished_at\x18\b \x01(\tR\vpublishedAt\x12!\n" +
	"\fupvote_count\x18\t \x01(\x05R\vupvoteCount\x12\x1d\n" +
	"\n" +
	"is_upvoted\x18\n" +
	" \x01(\bR\tisUpvoted\x12\x1d\n" +
	"\n" +
	"view_count\x18\v \x01(\x05R\tviewCount\x12\x1b\n" +
	"\tis_viewed\x18\f \x01(\bR\bisViewed\x12(\n" +
	"\x10latest_viewed_at\x18\r \x01(\tR\x0elatestViewedAt\x12\x1f\n" +
	"\vcategory_id\x18\x0e \x01(\x04R\n" +
	"categoryId\x12\x17\n" +
	"\atag_ids\x18\x0f \x03(\tR\x06tagIds\x12&\n" +
	"\x04user\x18\x10 \x01(\v2\x12.grpc.UserResponseR\x04user\"o\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl2\xa7\x01\n" +
	"\x0eArticleService\x12H\n" +
	"\rGetAllArticle\x12\x1a.grpc.GetAllArticleRequest\x1a\x1b.grpc.GetAllArticleResponse\x12K\n" +
	"\x0eGetArticleById\x12\x1b.grpc.GetArticleByIdRequest\x1a\x1c.grpc.GetArticleByIdResponseB;Z9github.com/asfung/ticus/internal/app/adapter/inbound/grpcb\x06proto3"

var (
	file_internal_app_adapter_inbound_grpc_article_proto_rawDescOnce sync.Once
	file_internal_app_adapter_inbound_grpc_article_proto_rawDescData []byte
)

func file_internal_app_adapter_inbound_grpc_article_proto_rawDescGZIP() []byte {
	file_internal_app_adapter_inbound_grpc_article_proto_rawDescOnce.Do(func() {
		file_internal_app_adapter_inbound_grpc_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_adapter_inbound_grpc_article_proto_rawDesc), len(file_internal_app_adapter_inbound_grpc_article_proto_rawDesc)))
	})
	return file_internal_app_adapter_inbound_grpc_article_proto_rawDescData
}

var file_internal_app_adapter_inbound_grpc_article_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_app_adapter_inbound_grpc_article_proto_goTypes = []any{
	(*GetAllArticleRequest)(nil),   // 0: grpc.GetAllArticleRequest
	(*GetAllArticleResponse)(nil),  // 1: grpc.GetAllArticleResponse
	(*GetArticleByIdRequest)(nil),  // 2: grpc.GetArticleByIdRequest
	(*GetArticleByIdResponse)(nil), // 3: grpc.GetArticleByIdResponse
	(*ArticleResponse)(nil),        // 4: grpc.ArticleResponse
	(*UserResponse)(nil),           // 5: grpc.UserResponse
}
var file_internal_app_adapter_inbound_grpc_article_proto_depIdxs = []int32{
	4, // 0: grpc.GetAllArticleResponse.articles:type_name -> grpc.ArticleResponse
	4, // 1: grpc.GetArticleByIdResponse.article:type_name -> grpc.ArticleResponse
	5, // 2: grpc.ArticleResponse.user:type_name -> grpc.UserResponse
	0, // 3: grpc.ArticleService.GetAllArticle:input_type -> grpc.GetAllArticleRequest
	2, // 4: grpc.ArticleService.GetArticleById:input_type -> grpc.GetArticleByIdRequest
	1, // 5: grpc.ArticleService.GetAllArticle:output_type -> grpc.GetAllArticleResponse
	3, // 6: grpc.ArticleService.GetArticleById:output_type -> grpc.GetArticleByIdResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_app_adapter_inbound_grpc_article_proto_init() }
func file_internal_app_adapter_inbound_grpc_article_proto_init() {
	if File_internal_app_adapter_inbound_grpc_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_adapter_inbound_grpc_article_proto_rawDesc), len(file_internal_app_adapter_inbound_grpc_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_adapter_inbound_grpc_article_proto_goTypes,
		DependencyIndexes: file_internal_app_adapter_inbound_grpc_article_proto_depIdxs,
		MessageInfos:      file_internal_app_adapter_inbound_grpc_article_proto_msgTypes,
	}.Build()
	File_internal_app_adapter_inbound_grpc_article_proto = out.File
	file_internal_app_adapter_inbound_grpc_article_proto_goTypes = nil
	file_internal_app_adapter_inbound_grpc_article_proto_depIdxs = nil
}
